### PR TITLE
Update sinusoidal_lightcurve.py

### PR DESCRIPTION
**Pull request by bernardinelli**
Fix sine wave implementation....

## Change Description

- [ ] My PR includes a link to the issue that I am addressing

## Code Quality
- [ ] I have read the Contribution Guide
- [ ] My code follows the code style of this project
- [ ] My code builds (or compiles) cleanly without any errors or warnings
- [ ] My code contains relevant comments and necessary documentation

### Bug Fix Checklist
- [ ] My fix includes a new test that breaks as a result of the bug (if possible)
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### New Feature Checklist
- [ ] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### Documentation Change Checklist
- [ ] Any updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)

### Build/CI Change Checklist
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the README to reflect this
- [ ] If this is a new CI setup, I have added the associated badge to the README

### Other Change Checklist
- [ ] Any new or updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover any changes
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### CODE REVIEW

**Comment by drewoldag** [comment]
I pushed a commit that addresses the Lint CI step failing. But you'll probably want to update (and possibly expand upon) the unit test that is in: `.../tests/lightcurve/sinusoidal/test_sinusoidal.py:test_compute_simple`. 

Once you update the test, feel free to re-request a review, and I can approve it.

**Comment by bernardinelli** [comment]
Thanks - I completely forgot about the unit test! I'll come back to it in the next day or so

**Comment by drewoldag** [comment]
No rush, but I want to make sure this doesn't get stale. Do you think you'll have a chance to update the unit tests in the next week or so?

**Comment by bernardinelli** [comment]
Totally my bad - I was swamped with other projects. Unit tests have been updated now!

**Review by drewoldag — APPROVED** [review]
Looks ok to me.

**Pull request merged**
